version: '3.8'

services:
  backend:
    build: ./backend
    container_name: auto-spons-backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/api/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      
volumes:
  uploads:

networks:
  default:
    name: auto-spons-network
